nvim-telekasten/telekasten.nvim

README.md, lua/telekasten.lua
globals are somewhat harmful and should be avoided if possible. You should probably test if everything still works :)
I suggest you to setup luacheck like we have it in telescope: https://github.com/nvim-telescope/telescope.nvim/blob/master/.luacheckrc
I would also suggest you look into formatting. I suggest https://github.com/JohnnyMorganz/StyLua
Last thing you dont need to do `local vim = vim` just have to setup your lsp correctly ;) This should help (I assume you already have a on_attach fn and capabilities table)
```lua
local function get_lua_runtime()
local result = {}
for _, path in pairs(vim.api.nvim_list_runtime_paths()) do
local lua_path = path .. "/lua"
local stat = vim.loop.fs_stat(lua_path)
if stat and stat.type == "directory" then
result[lua_path] = true
end
end …
```
=> fix: no more globals

lua/telekasten.lua
This prevents repeating the extension if the user already inputs it with the title of the new note.
Before, if a user titled the new note as `mytitle.md` it would be created as `mytitle.md.md`
Now it is just `mytitle.md`.
=> fix: sanitize title input (prevent double extension)

lua/telekasten.lua
Using `[[wikilinks]]` notation, if the `find_file` (and similar) commands were called while the cursor was **on the first set** of square brackets, it would return `[filename]` instead of the expected `filename` due to the "yank inside brackets"
https://github.com/renerocksai/telekasten.nvim/blob/4914c9d639581aa24959a22bb0ac3f18b1a3fbc4/lua/telekasten.lua#L471
This would then raise an error as telekasten would be looking for a file called `[filename]` and not `filename`, which in turns will cause an issue with the `create_note`.
This PR removes the square brackets if they are completely surrounding the yanked string (while avoiding issues if the file has some words inside square brackets).
It may still cause an issue if the files are starting and finishing with some bracketed words, but …
=> fix: sanitize filesearch

lua/telekasten.lua
The link needs to be placed after the cursor, not before.
If the cursor is represented by `_` when using insert_link(), the following was happening
- `my text _` -> `my test[[link]]`
- `my text_` -> `my tex[[link]]t`
By inserting after the cursor, it behaves as one would normally expects.
=> fix: paste link after cursor

README.md, doc/telekasten.txt, lua/telekasten.lua
This adds multiple new template tokens for relative calendar offsets.  These are useful for creating templatized links in daily and weekly notes for navigating to notes along a timeline.  Additionally, it facilitates creating a weekly note template that can have links to the days for that week.
- prevday
- nextday
- prevweek
- nextweek
- isoweek (for consistency with prevweek and next week)
- days of the week by name
=> Feature template dates

lua/telekasten.lua
Calling create_note_from_template from follow_link to a nonexistent file throws and error because calendar_info isn't set before calling linesubst.  This adds a check and assumes that if no date information is passed that you want today's dates.
=> fix bug with create_note_from_template and nil calendar_info

lua/telekasten.lua
Goto_today() should look in the correct directory for daily entries. This is especially important if the journal directory is not a subdirectory of the zettelkasten home directory, as the daily notes were not appearing at all in that case.
=> fix: make goto_today() look for daily notes, not zettels

lua/telekasten.lua
The first time I tried to make a daily note was Dec 23rd.  I noticed that my note said 23th, not 23rd.  After investigating, I found this simple typo.  I didn't think it was worth creating an issue over.
=> Fixed day suffix - there's no 33rd, but there is a 23rd

lua/telekasten.lua
I want to be able to assign keybindings to specific search text so that I can quickly find kinds of things in my notes.
The first is with TODOs - implemented like this:
`nnoremap <leader>zg :lua require('telekasten').search_notes({default_text=[[- \[ \] ]]})`
I'll be using it for some tags as well and perhaps others might find it useful. 
I'm new to Lua so any feedback would be greatly appreciated. 
** will do the rest when I have time later on - not familiar with lua enough to do this quickly right now**
Happy to do this later if you'd like to merge.
=> Allow passing default_text opt to SearchNotes 

README.md, doc/telekasten.txt, lua/telekasten.lua
This PR fixes #71. I've added a function called `CleanPath` to `telekasten.lua` that takes the incoming `home` path (either default or set by the user in their config) and checks if it is a Windows path. If not, it returns the original path. If it is, it substitutes the path with a substring of the path that begins at the first folder delimiter (`\\` in Windows, `/` in Unix/Linux).
This change allows Windows users to use `vim.fn.expand('~\zettelkasten')` like in the default config (or any variation of the sort) without having to worry about `C:` messing up the file path.
- This PR fixes or closes issue: fixes #71
- This PR is related to issue: #71
=> Windows file path clean

README.md, doc/telekasten.txt, lua/telekasten.lua
This allows the user to specify if they want an UUID prefix in the filename of the new notes (`false`by default).
Two types of prefixes are supported:
- `rand`: a random 6-char string
- `<input for os.date()>` such as `%Y%m%d%H%M`(default)
- Related to discussion #56
-
=> Add UUID prefix to new notes

lua/taglinks/tagutils.lua, syntax/telekasten.vim
This allows the use of accented characters in the tags. Both tag search and tag highlight have been fixed.
The `[À-ÿ]` regex matches the following characters: `àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜçÇßØøÅåÆæ`, which should cover most cases. 
I think it could still be a good idea to rework it further so we could add full utf-8 support (in case people use Chinese or Russian alphabet, or even emoji maybe).
- This PR fixes or closes issue: fixes #86 
- [ x The `doc/telekasten.txt` helpfile has been updated according to this change.
=> fix: accents in tags closes #86

lua/taglinks/taglinks.lua
The current way of determining if an object is a link or a tag is not really great in my opinion. Basically, we start at the cursor, and look left. If the left char is a `[`, we look continue looking left. If it is again a `[`, we assume that the cursor is a zettel link.
There is therefore an issue with media links. These are formed by a pair of `[text](link)`. Starting somewhere in the link, we move left and find the first `[` (before text). If there is nothing else on that line, fine we return nil and assume it was a media link. If however there was an other occurrence of `[` ANYWHERE before that (in a Todo, as in #91, or with a proper wiki link (or any other link), the old routine would assume we are in a zettel link.
The quick fix implemented here just add a check to see if we have a …
=> fix: media links issue, closes #91

lua/telekasten.lua
This allow to look for backlinks that are in the form of `[[filename#something]]` instead of just `[[filename]]`.
=> fix: backlinks with headerlinks, closes 103

lua/taglinks/taglinks.lua
As discussed in #110, the way telekasten determines if we are in a link or a tag is probably suboptimal.
This PR solves #109 by allowing the user to place the cursor wherever they want when doing follow_link() and not just on the filename part.
- This PR fixes or closes issue: fixes #109 
Yes to all
=> fix: follow_links with headerlinks, closes 109

lua/telekasten.lua
The uuid was only being created if the title prefix option was set, which meant it couldn't be used in a template.
I'd originally thought that link yanks and link follows worked via searching for the uuid (as seen on zettelkasten.de sample notes), but I see now that it works on note title as implemented. This yields an interesting follow-on question: Is there any reason to ever include the uuid in a template? I had been planning on naming the notes by title, and including uuid in the yaml front matter.
=> Fix UUID when not in filename

README.md, doc/telekasten.txt, lua/taglinks/tagutils.lua, lua/telekasten.lua
Fix #145 for systems that do not have `rg --pcre2` available.
This PR unfortunately means that #115 will still be happening if people do not have `--pcre2` option for ripgrep on their system.
- This PR fixes or closes issue: fixes #145 
- This PR is related to issue: #115
=> Fix pcre2 issue with ripgrep (closes #145)

README.md, doc/telekasten.txt, lua/telekasten.lua
This PR implements a `shorttitle` option for template substitutions. When used, a note created in a sub directory such as `school/class/My New Note` becomes `My New Note`.
=> Feature: Short Title Template Substitutions

README.md, doc/telekasten.txt, lua/telekasten.lua, plugin/telekasten.vim
Edit x2: Fixed the original issue.
This PR lets users toggle todos from a visual range. Selecting a visual range then executing `:Telekasten toggle_todo` will
change every line of the range to a `todo` and correctly toggle existing `todo` lines with the next state. 
It passes the `-range` flag to the main `Telekasten` command in `telekasten.vim`. I do not know if this is the best way to pass
a range to the `toggle_todo` subcommand but this looked like the only way for Neovim to do it. The only consequences I see from
doing it like this is *possible* changing the behavior of other subcommands but as far as I could tell from testing, if you select
a visual range for a different command, the only line that is used is the last where the cursor ends up.
Please let me know if you need …
=> Added Toggling Todos in Visual Range

README.md, doc/telekasten.txt, lua/telekasten.lua
Quote from #188 
> I use telekasten.nvim with new_note_filename = uuid.
People who use telekasten.nvim with filename uuid like me must watch file contents one by one when using the current InsertLink function.
I guess Anyone sometimes wants to search a linking file with live grep.
- This PR fixes or closes issue: fixes #188 
- This PR is related to issue: #188
=> Add with live grep option to insert link function and find notes function

README.md, doc/telekasten.txt, lua/telekasten.lua
This PR adds the ability to provide a lua function that generates the UUID for a new note. This allows users to configure telekasten with something like e.g.
```lua
require("telekasten").setup({
uuid_type = os.time()
})
```
to create a filename with a unix time based UUID. While this `"unix"` timestamp option could be hardcoded as a `uuid_type`, passing any custom function allows users to define arbitrarily complex UUID patterns.
- This PR fixes or closes issue: N/A
- This PR is related to issue: N/A
=> Add custom function option for UUID generation

README.md, doc/telekasten.txt, lua/telekasten.lua
Adds two new template options, `{{time24}}` and `{{time12}}`, which allow users to inject the more precise time into their notes / journal entries. Personally, I like having additional context of the specific hour and minute for journal entries.
I tossed around the idea of implementing this feature as separate `{{hour}}`, `{{min}}`, `{{sec}}`, etc templates so users could build their own specific time representation, but at that point we're just re-implementing `os.date()` in our templating engine :laughing:. 
Another option is we could allow custom lua functions to be defined in the users configuration, run those functions when `create_note_from_template` is called, and merge the results into the existing `substs` table.
- This PR fixes or closes issue: N/A …
=> Add new precise time (hour:min:sec) templating options

lua/telekasten.lua
#231 describes an issue where creating a note from a template seem to fail for some users.
The failure occurs in `linesubst` when attempting to substitute the uuid. Instead of the expected string or nil value, it receives a boolean value which cannot be substituted in.
The reason for this boolean uuid stems from how the calls are made:  
`FindDailyNotes`, `FindWeeklyNotes`, `GotoDate` and `GotoThisWeek` all make a call to `create_note_from_template` similar to this:
```lua
create_note_from_template(title, _, fname, M.note_type_templates.weekly)
```
Where `_` is meant to represent a nil uuid.  
This in turn calls `linesubst` with the uuid provided. The issue is that `_` appears to have a boolean assigned to it. It's not clear whether this is a problem with this plugin, or elsewhere, but …
=> Fixed issue where notes created from templates would error if _ was previously set.

README.md, doc/telekasten.txt, lua/telekasten/utils/taglinks.lua, lua/telekasten/utils/tags.lua
This brings support for a new tag notation: `@tag`. This PR duplicates code from the `#tag` notation.
- This PR is related to issue: #143
=> Add @tag support

lua/telekasten.lua
set  `show_link_counts = false` in `FindAllTags` second prompt
Some users experience an empty dialog after calling show_tags, when the tag has been selected and a prompt with the files that contain the tag should appear.
My understanding is that the flag will call linkutils.generate_backlink_map to get a list of backlinks. I can't see the purpose for the count in the context of showing tags, so I believe that false should be the value for all cases
- This PR fixes or closes issue: fixes #226
=> fix show_tags for some users

lua/telekasten.lua
Saves the yank register to a local variable and set it back one done using it.
- This PR fixes or closes issue: fixes #184 
=> fix: TK functions no longer override default registers (#184)

doc/telekasten.txt, lua/telekasten.lua
Context inside commit messages and linked issues.
<details>
```
Author: Sleepful <josepablov@gmail.com>
Date:   Thu Jul 6 14:21:23 2023 -0600
Update check_dir_and_ask: async for vim.ui.select
vim.ui.select is meant to be used as an asynchronous operation,
in order to do this, it receives a callback as a third argument.
This commit adjusts check_dir_and_ask to leverage the asynchronous
usage of vim.ui.select, as a side effect to make this work, I also
refactored the code that depends on the function in order to leverage
the asynchronous operations.
References:
- https://github.com/stevearc/dressing.nvim/issues/80#issuecomment-1380734202
- https://github.com/stevearc/dressing.nvim
- https://github.com/neovim/neovim/pull/15771
Fixes:
- …
```
=> Create subdirs when creating new note

lua/telekasten.lua
When `FollowLink` is called from the `show_tags` picker, it searches for the word that was under the cursor instead of the selected tag. This PR changes `FollowLink` so it instead searches for the selected tag.
Fix `FollowLink` so it searches for the selected tag instead of the word under the cursor when invoked from the `show_tags` picker.
- This PR fixes or closes issue: fixes #281
=> Fix FollowLink when searching tags.

README.md, doc/telekasten.txt, syntax/telekasten.vim
This makes the highlighting of aliased wikilinks consistent with other wikilink highlighting.
Additionally, it condenses the syntax rules to streamline highlighting setup:
- removes `tkHighlightedAliasedLink` (this is now simply covered by `tkHighlight`)
- removes `tkLinkAlias` (which wasn't working correctly)
- renaming `tkLinkBody` to `tkAliasedLink` (`tkAliasedLink` was the rule that made highlighting inconsistent, and its rule is now covered by `tkLink`)
This change may break compatibility for users with `tkHighlightedAliasedLink`, `tkLinkAlias`, and `tkAliasedLink` highlight rules defined.
Given the Highlighting rules below:
```lua
cmd("hi tkBrackets ctermfg=gray guifg=gray")
cmd("hi tkLink ctermfg=72 guifg=#689d6a cterm=bold,underline gui=bold,underline")
cmd("hi tkLinkBody …
```
=> Make aliased wikilink highlighting consistent

doc/telekasten.txt, lua/telekasten.lua
A previous addition added the functionality to create a new note with `<C-n>` when using the `find_note` picker (see https://github.com/renerocksai/telekasten.nvim/issues/141 and https://github.com/renerocksai/telekasten.nvim/pull/230). While this is a nice addition, it interferes with the default key mappings of Telescope for moving up and down the list of results, which uses `<C-n>` and `<C-p>`. It would be nice to have a configuration setting to be able to disable this picker mapping, so that it does not interfere with the Telescope default.
I have not coded much Lua other than setting my own Neovim configuration, so I'm note sure if this proposed change is in line with how the plugin is generally written. It is a very simple addition: a new config setting and an if clause that checks …
=> Enable config for creation of new note with Ctrl-n

syntax/telekasten.vim
This change makes link syntax highlighting able to cross lines, see #303 for details.
- This PR is related to issue: #303
=> Allow link syntax highlights to cross lines

lua/telekasten.lua
This PR allows following line-split links if the cursor is on the first line of the split; see https://github.com/renerocksai/telekasten.nvim/issues/303#issuecomment-1959460689. I thought that it'd be good to have this very simple change, even if there is no easy way to get the same functionality on the second line of the split (which remains to be seen, I guess).
- This PR is related to issue: #303
=> Allow following line-split links on the first line

lua/telekasten.lua
changing the current working directory when creating a new note to the configured home directory
This addresses the feature/bug outlined in #293 
By changing the CWD before and after the new note prompt is shown, the desired behavior is achieved.
I don't think that this should negatively affect any users.
- This PR fixes or closes issue: fixes #293
=> feat(293): Tab autocompletes with folders in notes home directory

.luarc.json, lua/telekasten.lua, lua/telekasten/config.lua, lua/telekasten/utils/definitions.lua
Adds more type checking based on https://luals.github.io/wiki/ primarily to config.lua and refactors config.lua to have less unnecessary indirection. This should only modify config.lua internally. I tested by printing the config table that is returned from requiring config.lua and it looks correct, although I have a simple config, but it is merging the defaults with it still.
```lua
-- user config
{
options = {
home = "/home/ujisati/.notes",
plug_into_calendar = false
}
}
require"telekasten.config".debug()
-- returns
{
auto_set_filetype = true,
auto_set_syntax = true,
calendar_opts = {
calendar_mark = "left-fit",
calendar_monday = 1,
weeknm = 4
},
clipboard_program = "",
close_after_yanking = false,
command_palette_theme = "ivy",
dailies = "/home/ujisati/.notes", …
```
=> Refactor and type config.lua

lua/telekasten.lua
Replace hard-coded "Create weekly dir" in new folder creation prompt with more generic "Notes", resulting in the following:
- Previous: "Create weekly dir folder /home//projects/second-brain/foobar/ does not exist! Shall I create it?"
- New: "Notes folder /home/cameron/projects/second-brain/foobar/ does not exist! Shall I create it?"
- This PR fixes or closes issue: fixes #297
=> fix: remove hard-coded "weekly" in folder creation prompt

doc/telekasten.txt, lua/telekasten.lua
Add an option to cast the new filename to lowercase.
- This PR fixes or closes issue: closes 311
=> feat: add filename_small_case

lua/telekasten.lua
This PR makes so that generate_filename_note is used when renaming notes.
~It is now possible to go from a uuid-title/title-uuid to title or uuid or the
other way around -- note that when going from uuid to uuid-title/title-uuid the
old uuid will be used as a title and a new uuid will be created.~
~It is not possible going from title-uuid to uuid-title or vice-versa, since the
current implementation will consider the old title the new uuid and the old uuid
the new title.~
~In all cases in which the new implementation is unable to succeed, manual
renaming of the files will be needed.~
The following breaking changes are introduced:
1. `Telekasten rename_note` now passes only the filename without the uuid for
the user to edit, while now being affected by `filename_space_subst`.
- This PR …
=> feat: use generate_note_filename for renaming notes
