nvim-telekasten/telekasten.nvim

- README.md
My linter don't like these :-)
Thanx for the work, I just need to understand the Zettle now !
> [lint] Remove end of line spaces

- lua/telekasten.lua
Add date format follwing rfc3339 for templates.
Fix #61
> feat: add rfc3339 format for templates (fix #61)

- README.md
- doc/telekasten.txt
I forgot to add the doc when adding the feature in #62 . Sorry :sweat_smile:
> doc: add doc for RFC3339 template (see #62)

- README.md
- doc/telekasten.txt
- lua/telekasten.lua
This PR adds a function to rename a note on the fly. It also adds an option to automatically update all links pointing to the modified note.
- This PR is related to discussion: #56 
The PR is a *WORK IN PROGRESS*. It seems to be working ok for simple filenames. What is still to do
> Feat: Note renaming

- README.md
- doc/telekasten.txt
- lua/telekasten.lua
As discussed in #70 , this allows user to configure the special folders (`templates`, `dailies`, `weeklies`, `image_subdir`) as absolute paths or just subdir name.
- This PR is related to discussion: #70
> Feat: Support for absolute or relative path config

- README.md
- doc/telekasten.txt
- lua/telekasten.lua
I added an option (`sort`) to specify sorting when displaying notes.
Right now I only added the sorting feature by filename(`filename`) and modification(`modified`) date.
- This PR fixes or closes issue: fixes #85
> feat: Add sorting feature [#85]

- lua/telekasten.lua
By using [] we provide a character set rather than a direct match with ().
fixes #118
When creating a note title, replace only the last occurrence of an extension configured by the user (i.e. Filename.md -> Filename, Filename.md.md -> Filename.md).
- This PR fixes or closes issue: fixes #118 
- This PR is related to issue: #118 
Re: checklist - I am not sure if there's anything to do w/r/t the README or doc. I don't see a changelog so I assume we are all good there.
> fix: note title ending removed when it matches parts of extension

- README.md
- lua/telekasten.lua
Add option to automatically open journal entries without going through the telescope prompt.
- This PR fixes or closes issue: fixes #93 
> Add straight jump for journal entries (fixes #93)

- lua/telekasten.lua
Without hiding numbers and relative numbers, the week number indicator
is cut off. This update changes those to be hidden along with the signcol.
> Hide numbers on calendar display.

- lua/taglinks/tagutils.lua
Currently cannot use yaml-bare/:tag: if pcre2 is available. This change makes it look to the config setting first.
- This PR fixes or closes issue: NA
- This PR is related to issue: NA
> User setting ignored if pcre2 is available

- README.md
- lua/telekasten.lua
I use [sway](https://github.com/swaywm/sway) with [wl-clipboard](https://github.com/bugaevc/wl-clipboard) instead of xclip.
It looks like a good idea to support `paste_img_and_link` for users like myself ;) 
> Add wl-paste support

- README.md
> show_tags is listed twice

- README.md
- doc/telekasten.txt
- lua/telekasten.lua
#171 
- This PR fixes or closes issue: fixes 
- This PR is related to issue: #171
> Add follow_url_fallback config option

- doc/telekasten.txt
- lua/telekasten.lua
- syntax/telekasten.vim
This is the solution for #139 
I've tested this from my repo, seems okay. 
I have a cursor on the link: 
After I press `<leader>zz` (my alias for follow_link) I receive this: 
PS. I didn't check everything, but I'll be if you think these changes are ready to go. 
PPS. I guess I won't need to format this, because this change seems small. 
- This PR fixes or closes issue: fixes #139 
> WikiLink aliases

- README.md
- doc/telekasten.txt
- lua/telekasten.lua
This PR fixes the issue where selecting a visual range then doing `toggle_todo` on a different line will target the previously selected range. This works by passing a `v = true` option to the `toggle_todo` function that will let the function know to look for marks. This will be applied the visual mapping for the `toggle_todo`.
- This PR fixes or closes issue: fixes #178
> [FIX] Fixes wrong visual range for ToggleTodo

- README.md
- doc/telekasten.txt
- lua/telekasten.lua
Created a new PR since I deleted my fork and Github wouldn't let me reopen the old PR with a new fork.
Based on [previous feedback](https://github.com/renerocksai/telekasten.nvim/pull/195#issuecomment-1369783361), this PR adds a new configuration option, `filename_space_subst`, that replaces spaces in the filename when the title is used within the filename generation. This is done to avoid spaces in filenames, which often need to be escaped on unix-like systems. If set to `nil`, no substitution will be made. The option defaults to `nil` to avoid any changes for existing users.
- This PR fixes or closes issue: N/A
- This PR is related to issue: N/A
> Add `filename_space_subst` config option

- lua/telekasten.lua
x-special/nautilus-clipboard
copy
file:///var/run/vmblock-fuse/blockdir/ZNZ9a9/1675406331282.mp4
thie image is open nvim
> fix:fix show hello when open nvim in topleft

- lua/telekasten.lua
fix: #141 
While finding a note by name, if not found, we may press `ctrl-n` to create a new one, title will be auto-filled.
- This PR fixes or closes issue: fixes #141 
> Ctrl-n to create new note out of finding

- README.md
This updates the advanced usage/key mappings section to link to the wiki entry. It also fixes the code vim code block so that it displays properly.
> doc: update advanced usage, link to wiki

- lua/telekasten.lua
- lua/telekasten/utils/tags.lua
> Allow Chinese characters in tags

- doc/telekasten.txt
- lua/telekasten.lua
Customize insert image and preview image files list.
This is useful to add optional filetypes into filtered list (for example telescope-media-files optionally supporting svg preview).
With this solution user can control which media files he want to see in telescope windows.
- This PR fixes or closes issue: fixes #301
- This PR is related to issue: #301
> Add custom media_extensions support

- lua/telekasten.lua
- fixed a problem with `xclip` in linux (added `xsel`)
- This PR fixes or closes issue: https://github.com/renerocksai/telekasten.nvim/issues/131
- This PR is related to issue: https://github.com/renerocksai/telekasten.nvim/issues/131
> https://github.com/renerocksai/telekasten.nvim/issues/131

- doc/telekasten.txt
- lua/telekasten.lua
> Journal auto open fix (fix #324)

- doc/telekasten.txt
- lua/telekasten.lua
Allow the user to specify which clipboard program to use when pasting images from the clipboard. 
I refactored the code a little bit by putting all the clipboard commands in a lookup table. I also changed the docs. 
P.S.: this is my first time making a contribution to a plugin and I am not familiar with lua so let me know if there are any issues. I tested a bunch of cases on my end and it seems to work well. On my machine the `xsel` executable produces empty files while `xclip` works like a charm.
- [ x] New feature (thank you!)
- [ x] Documentation update
- This PR fixes or closes issue: fixes #320 
- This PR is related to issue: #320
> Refactor and add option to choose clipboard program

- lua/telekasten.lua
Correcting an issue where find daily/weekly notes would search the entire notes repo when the daily/weekly folder is set to the base notes folder. 
- added a search pattern for daily and weekly notes
- added a search depth parameter to limit searches to the base of the daily notes directory
- This PR fixes or closes issue: fixes #321 
> refs 321-daily-weekly-picker: feat: fix daily/weekly search when the folder is set to the base folder

- lua/telekasten.lua
Trim leading/trailing whitespace in subcommand. Currently an error occurs if you accidentally have an extra whitespace, e.g.:
"No such subcommand: `find_notes   `"
- [] The `README.md` has been updated according to this change.
- [] The `doc/telekasten.txt` helpfile has been updated according to this change.
> trim whitespace in subcommands

- lua/telekasten.lua
This PR pertains to #360 (a bug I opened recently). I was setting up your Zettelkasten tool and was finding that `:Telekasten rename_note` would rename the note file but not update the `[[links]]` to the renamed note in other notes or the front matter of the renamed note i.e. `{{title}}`.
**Summary of changes:**
1. Updated RenameNote function:
- Now updates the title: field in the current note's frontmatter
- Properly handles the buffer content before saving
2. Fixed rename_update_links function:
- Now uses the correct oldfile.title and newname parameters
- Added debugging output to track the operation
- Calls recursive_substitution with the right arguments
3. Enhanced recursive_substitution function:
- Added debugging output to show what's being searched and found
- Better error handling …
> Fix `rename_note` bugs to update `[[links]]` and `{{title}}` fields

- lua/telekasten.lua
- lua/telekasten/utils/files.lua
Fixes that the directory is not changed back after changing it once for the autocomplete of the note title.
Currently this is used for Create Note and Create Templeted Note so instead of doing at 2 places the code was also moved to the utility function for files which is anyways only used by these two and not anywhere else.
- This PR fixes or closes issue: fixes #355 
> fix: change cwd back to original (#355)
